apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-vault-secret
  namespace: default
spec:
  type: kv-v2
  mount: kv2
  path: data/cloudflare
  destination:
    name: cloudflare-token-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: static-auth
