apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-cloudflare
spec:
  provider: vault
  secretObjects:
  - data:
    - key: CF_DNS_API_TOKEN
      objectName: cloudflare-token
    secretName: cloudflare-token-secret
    type: Opaque
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    roleName: "database"
    objects: |
      - objectName: "cloudflare-token" 
        secretPath: "kv2/data/cloudflare"
        secretKey: "CF_DNS_API_TOKEN"

