logs:
  general:
    level: ERROR
ports:
  web: 
  websecure:
    tls:
      enabled: true
env:
- name: CF_DNS_API_TOKEN_FILE
  value: "/vault/secrets/cloudflare"
certResolvers:
  letsencrypt:
    email: basix@basix.tech
    dnsChallenge:
      provider: cloudflare
      resolvers:
        - 1.1.1.1
    storage: /data/acme.json
ingressRoute:
  dashboard:
    enabled: true
  healthcheck:
    enabled: true
persistence:
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: "/ssl-certs"
updateStrategy:
  type: Recreate
  rollingUpdate: 
deployment:
  podAnnotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-inject-secret-cloudflare-full: kv2/cloudflare
    vault.hashicorp.com/agent-inject-template-cloudflare: |
      {{`{{- with secret "kv2/cloudflare" -}}
      {{ .Data.data.CF_DNS_API_TOKEN }}
      {{- end }}`}}
    vault.hashicorp.com/role: traefik
    vault.hashicorp.com/log-level: debug
  initContainers:
  - name: volume-permissions
    image: busybox:1.36.1
    command: ["sh", "-c", "touch /ssl-certs/acme.json; chmod -v 600 /ssl-certs/acme.json"]
    volumeMounts:
    - name: ssl-certs
      mountPath: "/ssl-certs"
ingressClass:
  enabled: true
  isDefaultClass: true
