logs:
  general:
    level: ERROR

ports:
  web: 
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true

ingressRoute:
  healthcheck:
    enabled: true

deployment:
  replicas: 3

rbac:
  enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true
