additionalArguments:
- "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
- "--certificatesresolvers.cloudflare.acme.email=your-email@example.com"
- "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1"
- "--certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json"
logs:
  general:
    level: ERROR
ports:
  web: 
  websecure:
    tls:
      enabled: true
env:
- name: CF_DNS_API_TOKEN_FILE
  value: "/vault/secrets/cloudflare"
ingressRoute:
  dashboard:
    enabled: true
  healthcheck:
    enabled: true
persistence:
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: "/ssl-certs"
updateStrategy:
  type: Recreate
  rollingUpdate: 
deployment:
  podAnnotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-inject-template-cloudflare: |
      {{`{{- with secret "kv/cloudflare" -}}
      {{ .Data.Value }}
      {{- end }}`}}
    vault.hashicorp.com/role: traefik
    vault.hashicorp.com/log-level: debug
  # initContainers:
  # - name: volume-permissions
  #   image: busybox:1.36.1
  #   command:
  #   - sh
  #   - "-c"
  #   - chmod -Rv 600 /ssl-certs/*
  #   volumeMounts:
  #   - name: ssl-certs
  #     mountPath: "/ssl-certs"
ingressClass:
  enabled: true
  isDefaultClass: true
