ui:
  enabled: true
injector:
  enabled: true
  image:
    repository: hashicorp/vault-k8s
    tag: 1.4.1
serverTelemetry:
  serviceMonitor:
    enabled: true
server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
  logLevel: debug
  logFormat: standard
  config: |-
    {{ .Files.Get "config.hcl" }}
